server:
  port: 8086

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/home/ubuntu/usr/develop/data/bd/h2/db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        format_sql: true